// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcq-hYaB7vRWpnuw-Ri7WRw1wIwMkEIws',
    appId: '1:426529831338:web:870da12916ea9d1b24d3d3',
    messagingSenderId: '426529831338',
    projectId: 'guardianav1',
    authDomain: 'guardianav1.firebaseapp.com',
    storageBucket: 'guardianav1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB391AQxn9-Cv_J4ombQ9skM7iPOcsAvZ8',
    appId: '1:426529831338:android:e0693f19d8960f5424d3d3',
    messagingSenderId: '426529831338',
    projectId: 'guardianav1',
    storageBucket: 'guardianav1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BJLTjFYeTicnL4WQ7y3veYCmXM1LFrY',
    appId: '1:426529831338:ios:a72c57ac5a1269da24d3d3',
    messagingSenderId: '426529831338',
    projectId: 'guardianav1',
    storageBucket: 'guardianav1.appspot.com',
    iosBundleId: 'com.example.guardiana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5BJLTjFYeTicnL4WQ7y3veYCmXM1LFrY',
    appId: '1:426529831338:ios:ae8448fe49d5454724d3d3',
    messagingSenderId: '426529831338',
    projectId: 'guardianav1',
    storageBucket: 'guardianav1.appspot.com',
    iosBundleId: 'com.example.guardiana.RunnerTests',
  );
}
